[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  targetPort = 3000

# Headers now configured in public/_headers file
# This provides better precedence control and easier management
# Security headers: X-Frame-Options, X-XSS-Protection, Referrer-Policy, Permissions-Policy
# Cache headers: Static assets, API routes, favicons, sitemaps
# CSP headers: Handled by Astro experimental CSP (hash-based directives)